default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

stages:
  - build
  - release

build-image:
  stage: build
  script:
    - IMAGE_TAG=${CI_COMMIT_SHORT_SHA:-latest}
    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - echo "Built image: $CI_REGISTRY_IMAGE:$IMAGE_TAG"
  artifacts:
    expire_in: 1 hour
    reports:
      dotenv: build.env
  rules:
    - if: $CI_COMMIT_TAG == null

release-image:
  stage: release
  script:
    - IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  rules:
    - if: $CI_COMMIT_TAG
